source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.1'

# ignore all warnings from all pods
inhibit_all_warnings!
pod 'SVProgressHUD', '~>1.1.3'
pod 'MagicalRecord', '~>2.2'
pod 'AFNetworking', '~> 2.2'
pod 'ReactiveCocoa'
pod 'MBFaker'
pod 'SAMTextView'
pod 'QuickDialog', '~>0.9'
pod 'SMCalloutView', '~>1.1.2'
pod 'CorePlot', '~>1.6'
pod 'Mantle', '~> 2.0.6'
pod 'SecureNSUserDefaults', '~> 1.0.0'
pod 'OpenUDID', '~> 1.0.0'
pod 'RMErrorRecoveryAttempter', '~> 0.0.1'
pod 'RMDateSelectionViewController', '~> 1.2.1'
pod 'GoogleAnalytics'
pod 'HockeySDK', '~> 3.5.6'
pod 'CTAssetsPickerController',  '~> 2.9.3'
pod 'JSQMessagesViewController', '~> 7.2.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'IBActionSheet', '~> 0.0.2'
pod 'Branch', '~>0.10.0'
pod 'KiteJSONValidator'
pod 'GoogleSignIn', '~>3.0.0'
pod 'DeviceUtil', '~>1.2.2'
pod 'ZXingObjC', '~> 3.0'
pod 'MKUnits', '~> 2.2.1'
